---
- name: Install MySQL
  hosts: 192.168.33.106
  vars:
    mysql_root_password: my-secret-pw
    mysql_user_password: Passw0rd
  
  tasks:
    - name: Install required dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip
        - python-pymysql
    
    - name: Add official MySQL 5.7 ubuntu bionic repository
      apt_repository:
        repo: "deb https://repo.mysql.com/apt/ubuntu/dists/bionic/mysql-5.7/"
        state: present

    - name: Install MySQL dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - mysql-common
        - mysql-server
        - mysql-client

    - name: Start MySQL Service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Copy initial MySQL client config file, no password, for root
      copy:
        src: .my.cnf
        dest: /root/.my.cnf

    - name: update mysql root password for all root accounts
      become: true
      mysql_user:
        name: root
        host: "{{ item }}"
        password: "{{ mysql_root_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
      with_items:
        - 127.0.0.1
        - ::1
        - localhost
        - "{{ ansible_host }}"

    - name: Create `/root/.my.cnf` with root password credentials
      become: yes
      template:
        src:  my.cnf.j2
        dest: /root/.my.cnf
        owner: root
        mode: 0600

    - name: Create the MySQL database
      become: true
      mysql_db:
        name: "employee_db"
        state: present

    - name: Create database user
      become: true
      mysql_user:
        name: db_user
        password: "{{ mysql_user_password }}"
        priv: '*.*:ALL'
        state: present